steps:
  - name: golang:1.19
    entrypoint: go
    args: ["mod", "download"]

  - name: golang:1.19
    entrypoint: go
    args: ["test", "./..."]

  - name: 'gcr.io/cloud-builders/docker'
    args: [
      'build',
      '-t',
      'us-central1-docker.pkg.dev/${PROJECT_ID}/global-spanner-api-repository/global-spanner-api',
      '.',
    ]

  - name: 'gcr.io/cloud-builders/docker'
    args: [
      'push',
      'us-central1-docker.pkg.dev/${PROJECT_ID}/global-spanner-api-repository/global-spanner-api',
    ]
